version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: flyaway-db
    environment:
      POSTGRES_DB: flyaway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - flyaway_data:/var/lib/postgresql/data
volumes:
  flyaway_data: